version: "3"

dotenv: [".env"]

tasks:
  install:
    cmds:
      - uv sync --dev
      - uv run pre-commit install

  lint:
    cmds:
      - uv run ruff check .

  pre-commit-all:
    cmds:
      - uv run pre-commit run --all-files

  run:
    dir: lasso_select_demo
    cmds:
      - uv run reflex run

  typecheck:
    cmds:
      - uv run pyright

  test:
    cmds:
      - uv run pytest

  publish:
    preconditions:
      # Check environment variable
      - sh: test -n "$PYPI_TOKEN"
        msg: "PYPI_TOKEN is not set -- Add PYPI_TOKEN=... to .env file"
    cmds:
      - echo "Publishing to PyPI"
      - uv run reflex component publish --no-validate-project-info --token $PYPI_TOKEN
