version: "3"

tasks:
  lint:
    cmds:
      - uv run ruff check .

  pre-commit-all:
    cmds:
      - uv run pre-commit run --all-files

  run:
    dir: lasso_select_demo
    cmds:
      - uv run reflex run

  test:
    cmds:
      - uv run pytest
