name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.5"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lint
        run: task lint

      - name: Run typecheck
        run: task typecheck

      - name: Initialize Reflex
        run: uv run reflex init
        working-directory: lasso_select_demo

      - name: Install playwright
        run: uv run playwright install

      - name: Run tests
        run: task test
